<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions targetNamespace="http://www.tais.ru/"
                  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
        <xs:schema elementFormDefault="qualified" targetNamespace="http://www.tais.ru/"/>
    </wsdl:types>
</wsdl:definitions>
